name: Python Docker

on: push
jobs:
  build:
    runs-on: ubuntu-latest
    container: python:3.11.2
    steps:
    - run: python --version
    - uses: actions/checkout@v3
    - name: Install requirements.txt
      run: pip install -r requirements.txt
    - name: install Jinja2
      run: pip install --upgrade jinja2
    - name: Run a inline script
      run: python app.py  
